// <auto-generated />
using System;
using Dispatch.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dispatch.Infrastructure.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    [Migration("20260827160522_EscreventeDoProtocolo")]
    partial class EscreventeDoProtocolo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dispatch.Domain.Conferente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CargaAtual")
                        .HasColumnType("integer")
                        .HasColumnName("carga_atual");

                    b.Property<double>("JornadaHoras")
                        .HasColumnType("double precision")
                        .HasColumnName("jornada_horas");

                    b.Property<bool>("NaEscala")
                        .HasColumnType("boolean")
                        .HasColumnName("na_escala");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivel");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_conferentes");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_conferentes_usuario_id");

                    b.ToTable("conferentes", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("PrazoPosConferencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prazo_pos_tipo");

                    b.Property<string>("PrazoPreConferencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prazo_pre_tipo");

                    b.HasKey("Id")
                        .HasName("pk_equipes");

                    b.ToTable("equipes", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.Escrevente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_escreventes");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_escreventes_equipe_id");

                    b.ToTable("escreventes", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.LoteImportacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("etapa");

                    b.Property<DateTimeOffset>("ImportadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("importado_em");

                    b.Property<DateTimeOffset>("LinhaDeCorte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linha_de_corte");

                    b.Property<int>("TotalLinhas")
                        .HasColumnType("integer")
                        .HasColumnName("total_linhas");

                    b.HasKey("Id")
                        .HasName("pk_lotes_importacao");

                    b.ToTable("lotes_importacao", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.Protocolo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AndamentoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("andamento_em");

                    b.Property<Guid?>("DonoId")
                        .HasColumnType("uuid")
                        .HasColumnName("dono_id");

                    b.Property<Guid>("EscreventeId")
                        .HasColumnType("uuid")
                        .HasColumnName("escrevente_id");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("etapa");

                    b.Property<Guid?>("LoteImportacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_importacao_id");

                    b.Property<string>("MotivoExcecao")
                        .HasColumnType("text")
                        .HasColumnName("motivo_excecao");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("Prazo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prazo_tipo");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TipoAtoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_ato_id");

                    b.Property<DateTimeOffset?>("VencimentoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vencimento_em");

                    b.HasKey("Id")
                        .HasName("pk_protocolos");

                    b.HasIndex("DonoId")
                        .HasDatabaseName("ix_protocolos_dono_id");

                    b.HasIndex("EscreventeId")
                        .HasDatabaseName("ix_protocolos_escrevente_id");

                    b.HasIndex("LoteImportacaoId")
                        .HasDatabaseName("ix_protocolos_lote_importacao_id");

                    b.HasIndex("TipoAtoId")
                        .HasDatabaseName("ix_protocolos_tipo_ato_id");

                    b.ToTable("protocolos", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.TipoAto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tipos_ato");

                    b.ToTable("tipos_ato", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("papel");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Dispatch.Infrastructure.Persistencia.RegraAlcadaRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlvoEtapa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alvo_etapa");

                    b.Property<Guid?>("AlvoTipoAtoId")
                        .HasColumnType("uuid")
                        .HasColumnName("alvo_tipo_ato_id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origem");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("permissao");

                    b.Property<Guid?>("SujeitoConferenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("sujeito_conferente_id");

                    b.Property<string>("SujeitoNivel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sujeito_nivel");

                    b.HasKey("Id")
                        .HasName("pk_regras_alcada");

                    b.ToTable("regras_alcada", null, t =>
                        {
                            t.HasCheckConstraint("ck_regras_alcada_alvo", "num_nonnulls(alvo_etapa, alvo_tipo_ato_id) = 1");

                            t.HasCheckConstraint("ck_regras_alcada_sujeito", "num_nonnulls(sujeito_conferente_id, sujeito_nivel) = 1");
                        });
                });

            modelBuilder.Entity("Dispatch.Domain.Conferente", b =>
                {
                    b.HasOne("Dispatch.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conferentes_usuarios_usuario_id");
                });

            modelBuilder.Entity("Dispatch.Domain.Escrevente", b =>
                {
                    b.HasOne("Dispatch.Domain.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_escreventes_equipes_equipe_id");
                });

            modelBuilder.Entity("Dispatch.Domain.Protocolo", b =>
                {
                    b.HasOne("Dispatch.Domain.Conferente", null)
                        .WithMany()
                        .HasForeignKey("DonoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_protocolos_conferentes_dono_id");

                    b.HasOne("Dispatch.Domain.Escrevente", null)
                        .WithMany()
                        .HasForeignKey("EscreventeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_protocolos_escreventes_escrevente_id");

                    b.HasOne("Dispatch.Domain.LoteImportacao", null)
                        .WithMany()
                        .HasForeignKey("LoteImportacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_protocolos_lotes_importacao_lote_importacao_id");

                    b.HasOne("Dispatch.Domain.TipoAto", null)
                        .WithMany()
                        .HasForeignKey("TipoAtoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_protocolos_tipos_ato_tipo_ato_id");
                });
#pragma warning restore 612, 618
        }
    }
}
