// <auto-generated />
using System;
using Dispatch.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dispatch.Infrastructure.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    partial class DispatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dispatch.Domain.Conferente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CargaAtual")
                        .HasColumnType("integer")
                        .HasColumnName("carga_atual");

                    b.Property<bool>("NaEscala")
                        .HasColumnType("boolean")
                        .HasColumnName("na_escala");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivel");

                    b.HasKey("Id")
                        .HasName("pk_conferentes");

                    b.ToTable("conferentes", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.Equipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("PrazoPosConferencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prazo_pos_tipo");

                    b.Property<string>("PrazoPreConferencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prazo_pre_tipo");

                    b.HasKey("Id")
                        .HasName("pk_equipes");

                    b.ToTable("equipes", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.Escrevente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("EquipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipe_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_escreventes");

                    b.HasIndex("EquipeId")
                        .HasDatabaseName("ix_escreventes_equipe_id");

                    b.ToTable("escreventes", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.Protocolo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("etapa");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Prazo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prazo_tipo");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridade");

                    b.Property<Guid>("TipoAtoId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_ato_id");

                    b.Property<DateTimeOffset?>("VencimentoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vencimento_em");

                    b.HasKey("Id")
                        .HasName("pk_protocolos");

                    b.HasIndex("TipoAtoId")
                        .HasDatabaseName("ix_protocolos_tipo_ato_id");

                    b.ToTable("protocolos", (string)null);
                });

            modelBuilder.Entity("Dispatch.Domain.TipoAto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tipos_ato");

                    b.ToTable("tipos_ato", (string)null);
                });

            modelBuilder.Entity("Dispatch.Infrastructure.Persistencia.RegraAlcadaRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlvoEtapa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alvo_etapa");

                    b.Property<Guid?>("AlvoTipoAtoId")
                        .HasColumnType("uuid")
                        .HasColumnName("alvo_tipo_ato_id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Permissao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("permissao");

                    b.Property<Guid?>("SujeitoConferenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("sujeito_conferente_id");

                    b.Property<string>("SujeitoNivel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sujeito_nivel");

                    b.HasKey("Id")
                        .HasName("pk_regras_alcada");

                    b.ToTable("regras_alcada", null, t =>
                        {
                            t.HasCheckConstraint("ck_regras_alcada_alvo", "num_nonnulls(alvo_etapa, alvo_tipo_ato_id) = 1");

                            t.HasCheckConstraint("ck_regras_alcada_sujeito", "num_nonnulls(sujeito_conferente_id, sujeito_nivel) = 1");
                        });
                });

            modelBuilder.Entity("Dispatch.Domain.Escrevente", b =>
                {
                    b.HasOne("Dispatch.Domain.Equipe", null)
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_escreventes_equipes_equipe_id");
                });

            modelBuilder.Entity("Dispatch.Domain.Protocolo", b =>
                {
                    b.HasOne("Dispatch.Domain.TipoAto", null)
                        .WithMany()
                        .HasForeignKey("TipoAtoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_protocolos_tipos_ato_tipo_ato_id");
                });
#pragma warning restore 612, 618
        }
    }
}
